### ISSUE TITLE
add functionality

### ISSUE THREAD

**Issue by whoisbroken** [YaroslavPikiner/js_task#10]
https://github.com/YaroslavPikiner/js_task/blob/fb7b4465897a417adeb2a6fdbe4f444f110aff9c/index.js#L148

method doesn't work with map and set
```
var s = new Set(['foo', window]);
Array.from(s);
// ['foo', window]
```
```
var m = new Map([[1, 2], [2, 4], [4, 8]]);
Array.from(m);
// [[1, 2], [2, 4], [4, 8]]
```
check it

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by YaroslavPikiner** [comment]
fixed
