### ISSUE TITLE
es6 template string

### ISSUE THREAD

**Issue by whoisbroken** [YaroslavPikiner/js_task#12]
https://github.com/YaroslavPikiner/js_task/blob/fb7b4465897a417adeb2a6fdbe4f444f110aff9c/index.js#L59

for polyfill we cant use es6 syntax.
look mdn case
```
if (typeof callback !== 'function') {
      throw new TypeError(callback + ' is not a function');
  }
```

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

**Comment by YaroslavPikiner** [comment]
fixed
